/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartoesRouteImport } from './routes/cartoes'
import { Route as CertoIaRouteImport } from './routes/certo-ia'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartoesRoute = CartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CertoIaRoute = CertoIaRouteImport.update({
  id: '/certo-ia',
  path: '/certo-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/certo-ia': typeof CertoIaRoute
  '/contas': typeof ContasRoute
  '/dashboard': typeof DashboardRoute
  '/despesas': typeof DespesasRoute
  '/investimentos': typeof InvestimentosRoute
  '/metas': typeof MetasRoute
  '/receitas': typeof ReceitasRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/certo-ia': typeof CertoIaRoute
  '/contas': typeof ContasRoute
  '/dashboard': typeof DashboardRoute
  '/despesas': typeof DespesasRoute
  '/investimentos': typeof InvestimentosRoute
  '/metas': typeof MetasRoute
  '/receitas': typeof ReceitasRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/certo-ia': typeof CertoIaRoute
  '/contas': typeof ContasRoute
  '/dashboard': typeof DashboardRoute
  '/despesas': typeof DespesasRoute
  '/investimentos': typeof InvestimentosRoute
  '/metas': typeof MetasRoute
  '/receitas': typeof ReceitasRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cartoes'
    | '/certo-ia'
    | '/contas'
    | '/dashboard'
    | '/despesas'
    | '/investimentos'
    | '/metas'
    | '/receitas'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cartoes'
    | '/certo-ia'
    | '/contas'
    | '/dashboard'
    | '/despesas'
    | '/investimentos'
    | '/metas'
    | '/receitas'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/cartoes'
    | '/certo-ia'
    | '/contas'
    | '/dashboard'
    | '/despesas'
    | '/investimentos'
    | '/metas'
    | '/receitas'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartoesRoute: typeof CartoesRoute
  CertoIaRoute: typeof CertoIaRoute
  ContasRoute: typeof ContasRoute
  DashboardRoute: typeof DashboardRoute
  DespesasRoute: typeof DespesasRoute
  InvestimentosRoute: typeof InvestimentosRoute
  MetasRoute: typeof MetasRoute
  ReceitasRoute: typeof ReceitasRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartoes': {
      id: '/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof CartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certo-ia': {
      id: '/certo-ia'
      path: '/certo-ia'
      fullPath: '/certo-ia'
      preLoaderRoute: typeof CertoIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartoesRoute: CartoesRoute,
  CertoIaRoute: CertoIaRoute,
  ContasRoute: ContasRoute,
  DashboardRoute: DashboardRoute,
  DespesasRoute: DespesasRoute,
  InvestimentosRoute: InvestimentosRoute,
  MetasRoute: MetasRoute,
  ReceitasRoute: ReceitasRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
